int8_t ng_irq_map[]={
  [WWDG_IRQn]                   = -1,     /*!< Window WatchDog Interrupt                                         */
  [PVD_IRQn]                    = -1,     /*!< PVD through EXTI Line detection Interrupt                         */
  [TAMP_STAMP_IRQn]             = -1,     /*!< Tamper and TimeStamp interrupts through the EXTI line             */
  [RTC_WKUP_IRQn]               = -1,     /*!< RTC Wakeup interrupt through the EXTI line                        */
  [FLASH_IRQn]                  = -1,     /*!< FLASH global Interrupt                                            */
  [RCC_IRQn]                    = -1,     /*!< RCC global Interrupt                                              */
  [EXTI0_IRQn]                  = -1,     /*!< EXTI Line0 Interrupt                                              */
  [EXTI1_IRQn]                  = -1,     /*!< EXTI Line1 Interrupt                                              */
  [EXTI2_IRQn]                  = -1,     /*!< EXTI Line2 Interrupt                                              */
  [EXTI3_IRQn]                  = -1,     /*!< EXTI Line3 Interrupt                                              */
  [EXTI4_IRQn]                  = -1,     /*!< EXTI Line4 Interrupt                                              */
  [DMA1_Stream0_IRQn]           = -2,     /*!< DMA1 Stream 0 global Interrupt                                    */
  [DMA1_Stream1_IRQn]           = -2,     /*!< DMA1 Stream 1 global Interrupt                                    */
  [DMA1_Stream2_IRQn]           = -2,     /*!< DMA1 Stream 2 global Interrupt                                    */
  [DMA1_Stream3_IRQn]           = -2,     /*!< DMA1 Stream 3 global Interrupt                                    */
  [DMA1_Stream4_IRQn]           = -2,     /*!< DMA1 Stream 4 global Interrupt                                    */
  [DMA1_Stream5_IRQn]           = -2,     /*!< DMA1 Stream 5 global Interrupt                                    */
  [DMA1_Stream6_IRQn]           = -2,     /*!< DMA1 Stream 6 global Interrupt                                    */
  [ADC_IRQn]                    = -1,     /*!< ADC1, ADC2 and ADC3 global Interrupts                             */
  [CAN1_TX_IRQn]                = -1,     /*!< CAN1 TX Interrupt                                                 */
  [CAN1_RX0_IRQn]               = -1,     /*!< CAN1 RX0 Interrupt                                                */
  [CAN1_RX1_IRQn]               = -1,     /*!< CAN1 RX1 Interrupt                                                */
  [CAN1_SCE_IRQn]               = -1,     /*!< CAN1 SCE Interrupt                                                */
  [EXTI9_5_IRQn]                = -1,     /*!< External Line[9:5] Interrupts                                     */
  [TIM1_BRK_TIM9_IRQn]          = -1,     /*!< TIM1 Break interrupt and TIM9 global interrupt                    */
  [TIM1_UP_TIM10_IRQn]          = -1,     /*!< TIM1 Update Interrupt and TIM10 global interrupt                  */
  [TIM1_TRG_COM_TIM11_IRQn]     = -1,     /*!< TIM1 Trigger and Commutation Interrupt and TIM11 global interrupt */
  [TIM1_CC_IRQn]                = -1,     /*!< TIM1 Capture Compare Interrupt                                    */
  [TIM2_IRQn]                   = -1,     /*!< TIM2 global Interrupt                                             */
  [TIM3_IRQn]                   = -1,     /*!< TIM3 global Interrupt                                             */
  [TIM4_IRQn]                   = -1,     /*!< TIM4 global Interrupt                                             */
  [I2C1_EV_IRQn]                = -1,     /*!< I2C1 Event Interrupt                                              */
  [I2C1_ER_IRQn]                = -1,     /*!< I2C1 Error Interrupt                                              */
  [I2C2_EV_IRQn]                = -1,     /*!< I2C2 Event Interrupt                                              */
  [I2C2_ER_IRQn]                = -1,     /*!< I2C2 Error Interrupt                                              */
  [SPI1_IRQn]                   = -1,     /*!< SPI1 global Interrupt                                             */
  [SPI2_IRQn]                   = -1,     /*!< SPI2 global Interrupt                                             */
  [USART1_IRQn]                 = -1,     /*!< USART1 global Interrupt                                           */
  [USART2_IRQn]                 = -1,     /*!< USART2 global Interrupt                                           */
  [USART3_IRQn]                 = -1,     /*!< USART3 global Interrupt                                           */
  [EXTI15_10_IRQn]              = -1,     /*!< External Line[15:10] Interrupts                                   */
  [RTC_Alarm_IRQn]              = -1,     /*!< RTC Alarm (A and B) through EXTI Line Interrupt                   */
  [OTG_FS_WKUP_IRQn]            = -1,     /*!< USB OTG FS Wakeup through EXTI line interrupt                     */
  [TIM8_BRK_TIM12_IRQn]         = -1,     /*!< TIM8 Break Interrupt and TIM12 global interrupt                   */
  [TIM8_UP_TIM13_IRQn]          = -1,     /*!< TIM8 Update Interrupt and TIM13 global interrupt                  */
  [TIM8_TRG_COM_TIM14_IRQn]     = -1,     /*!< TIM8 Trigger and Commutation Interrupt and TIM14 global interrupt */
  [TIM8_CC_IRQn]                = -1,     /*!< TIM8 Capture Compare global interrupt                             */
  [DMA1_Stream7_IRQn]           = -1,     /*!< DMA1 Stream7 Interrupt                                            */
  [FSMC_IRQn]                   = -1,     /*!< FSMC global Interrupt                                             */
  [SDIO_IRQn]                   = -1,     /*!< SDIO global Interrupt                                             */
  [TIM5_IRQn]                   = -1,     /*!< TIM5 global Interrupt                                             */
  [SPI3_IRQn]                   = -1,     /*!< SPI3 global Interrupt                                             */
  [UART4_IRQn]                  = -1,     /*!< UART4 global Interrupt                                            */
  [UART5_IRQn]                  = -1,     /*!< UART5 global Interrupt                                            */
  [TIM6_DAC_IRQn]               = -1,     /*!< TIM6 global and DAC1&2 underrun error  interrupts                 */
  [TIM7_IRQn]                   = -1,     /*!< TIM7 global interrupt                                             */
  [DMA2_Stream0_IRQn]           = -2,     /*!< DMA2 Stream 0 global Interrupt                                    */
  [DMA2_Stream1_IRQn]           = -2,     /*!< DMA2 Stream 1 global Interrupt                                    */
  [DMA2_Stream2_IRQn]           = -2,     /*!< DMA2 Stream 2 global Interrupt                                    */
  [DMA2_Stream3_IRQn]           = -2,     /*!< DMA2 Stream 3 global Interrupt                                    */
  [DMA2_Stream4_IRQn]           = -2,     /*!< DMA2 Stream 4 global Interrupt                                    */
  [ETH_IRQn]                    = -1,     /*!< Ethernet global Interrupt                                         */
  [ETH_WKUP_IRQn]               = -1,     /*!< Ethernet Wakeup through EXTI line Interrupt                       */
  [CAN2_TX_IRQn]                = -1,     /*!< CAN2 TX Interrupt                                                 */
  [CAN2_RX0_IRQn]               = -1,     /*!< CAN2 RX0 Interrupt                                                */
  [CAN2_RX1_IRQn]               = -1,     /*!< CAN2 RX1 Interrupt                                                */
  [CAN2_SCE_IRQn]               = -1,     /*!< CAN2 SCE Interrupt                                                */
  [OTG_FS_IRQn]                 = -1,     /*!< USB OTG FS global Interrupt                                       */
  [DMA2_Stream5_IRQn]           = -2,     /*!< DMA2 Stream 5 global interrupt                                    */
  [DMA2_Stream6_IRQn]           = -2,     /*!< DMA2 Stream 6 global interrupt                                    */
  [DMA2_Stream7_IRQn]           = -2,     /*!< DMA2 Stream 7 global interrupt                                    */
  [USART6_IRQn]                 = -1,     /*!< USART6 global interrupt                                           */
  [I2C3_EV_IRQn]                = -1,     /*!< I2C3 event interrupt                                              */
  [I2C3_ER_IRQn]                = -1,     /*!< I2C3 error interrupt                                              */
  [OTG_HS_EP1_OUT_IRQn]         = -1,     /*!< USB OTG HS End Point 1 Out global interrupt                       */
  [OTG_HS_EP1_IN_IRQn]          = -1,     /*!< USB OTG HS End Point 1 In global interrupt                        */
  [OTG_HS_WKUP_IRQn]            = -1,     /*!< USB OTG HS Wakeup through EXTI interrupt                          */
  [OTG_HS_IRQn]                 = -1,     /*!< USB OTG HS global interrupt                                       */
  [DCMI_IRQn]                   = -1,     /*!< DCMI global interrupt                                             */
  [RNG_IRQn]                    = -1,     /*!< RNG global Interrupt                                              */
  [FPU_IRQn]                    = -1      /*!< FPU global interrupt                                               */

}



